

name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee


      #- name: Build
      #  run: ./gradlew build

      - name: Test
        run: ./gradlew  test

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: build/reports
